### ISSUE TITLE
Persistence of ladybirds at the monad level

### ISSUE THREAD

**Issue by msjitlal** [BiologicalRecordsCentre/BRCtracker#10]
All nine species of interest (that I’ve so far examined) have a ratio < 0.5 for:

 unique(monads) / unique(monad/year combinations)

i.e. for all nine species, over half the monads have just a single year in which they are recorded. Given the persistence issue raised before, it may be better to concentrate on the quadrant records.

**Comment by drnickisaac** [comment]
No, I disagree. The absolute number of monads with repeats is still large. I would much rather use this subset than go to a coarser resolution. At quadrant scale you would have to assume that visits to nearby monads (within one quadrant) were sampling the same ladybird population. I don't feel comfortable with that kind of approximation, just for the sake of using all the data.
