### ISSUE TITLE
DF website: unable to edit 'body' text for some nodes

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/BRCtracker#101]
Users who have editing rights are unable to edit the 'body' text for some nodes, but are able to do so for others. I cannot see what makes it possible it some cases and not in others.

For example, these two nodes were created at more or less the same time in the same way:
- https://www.dipterists.org.uk/node/152/edit - users with editing permission can **not** edit this page
- https://www.dipterists.org.uk/node/153/edit - users with editing permission **can** edit this page

**Comment by kitenetter** [comment]
Hi @BirenRathod is there any chance of fixing this? I keep getting asked about it by people who want to be able to edit the website.

**Comment by BirenRathod** [comment]
@kitenetter 

People who got **Editor** role could able to add, edit & delete any page, so please allocate that role with others.

**Comment by BirenRathod** [comment]
@kitenetter 

Sorry not allowing to delete any content but their own content.

**Comment by kitenetter** [comment]
@BirenRathod the problem is that users who have been given editing permissions are still not allowed to edit the "body" part of many of the pages. They do get an "Edit" tab on the relevant pages, but the "Body" area is greyed out:

![image](https://user-images.githubusercontent.com/16039111/52953366-2bc98100-337f-11e9-9297-d2661cb56bc5.png)

**Comment by BirenRathod** [comment]
@kitenetter 
Could you send me a example of that user please?

**Comment by kitenetter** [comment]
Now fixed (problem was to do with the use of Basic HTML vs Full HTML, and Biren has now disallowed the former). Closing.
