### ISSUE TITLE
DF website - 'view' for orders is not working

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/BRCtracker#103]
When orders are added to the website, it is possible for admins to edit those orders, but the 'view' tab is generating an error message "The website encountered an unexpected error. Please try again later." See for example:
https://www.dipterists.org.uk/admin/commerce/orders/429

**Comment by BirenRathod** [comment]
@kitenetter 
Rabbit hole module was causing to access that page. I have uninstalled rabbit hole module at present. As I don't see any benefit of using that. Do let me you have any specific need of it or if any of the page causing to see appear.

**Comment by BirenRathod** [comment]
@BirenRathod 
Rabbit hole is very heavy module to do this job. You could simply restrict this page by editing the menu link from this link -> https://www.dipterists.org.uk/admin/structure/menu/manage/main

**Comment by BirenRathod** [comment]
@kitenetter 

I have implemented the permission, so it is only available for members only.

**Comment by kitenetter** [comment]
Thanks @BirenRathod - fairly sure I was only using rabbit hole because you told me to! But happy not to have to use it, and thanks for setting up the alternative permissions. Closing.

**Comment by BirenRathod** [comment]
@kitenetter 
Yes, no doubt about it but found out that rabbit hole module has caused problem. So alternative permission is a better solution.
