### ISSUE TITLE
BRC Treelogs - problem with page refresh

### ISSUE THREAD

**Issue by mjopocock** [BiologicalRecordsCentre/BRCtracker#105]
I can now view the photos on the results page and can scroll through the different results pages.

However, if I leave the page inactive for a while and then try to view a different page of results, I have the error message: "The data did not load successfully. The reason given was: Unauthorised".

If I press refresh on the browser, it then loads successfully. But is there a way to avoid this problem?

Thanks.

**Comment by BirenRathod** [comment]
@mjopocock 
Keep checking this and I found no problem.

**Comment by DavidRoy** [comment]
@mjopocock and this one
