### ISSUE TITLE
BRC Treelogs - add new sites to data input

### ISSUE THREAD

**Issue by mjopocock** [BiologicalRecordsCentre/BRCtracker#106]
Hi @BirenRathod,
@DavidRoy 

For the next stage of the Treelogs project, we will be setting this up at 2 new sites.

Could you add a drop down box for the 'Site Name' and call the new sites "Dovedale 1 (Lovers Leap), Derbyshire"  and "Dovedale 2 (Nabs Wood), Derbyshire"

The lat/long for the new sites are 
Dovedale 1 (Lovers Leap) 53.066920, -1.783319
Dovedale 2 (Nabs Wood) 53.079245, -1.787000

Thanks. I'll open a separate issue about the results.
Michael

**Comment by BirenRathod** [comment]
@mjopocock 
New sites have been added to survey form.

**Comment by BirenRathod** [comment]
@mjopocock 
If you don't find any problem, could you please close this.

**Comment by DavidRoy** [comment]
@mjopocock another one
