### ISSUE TITLE
BRC Treelogs - results not sorted by date

### ISSUE THREAD

**Issue by mjopocock** [BiologicalRecordsCentre/BRCtracker#108]
Hi @BirenRathod 
@DavidRoy 

The Treelogs results page is not correctly sorted by date. I wonder if it is sorted by 'submission date' instead of selected date?

Thanks,
Michael

**Comment by BirenRathod** [comment]
@mjopocock 
Result has been implemented now to show images as per submitted date.

**Comment by DavidRoy** [comment]
@mjopocock can you review Treelogs issues and close if fixed
