### ISSUE TITLE
BRC records to be examined

### ISSUE THREAD

**Issue by msjitlal** [BiologicalRecordsCentre/BRCtracker#11]
Please can you define which taxonomic (sub-)groups are to be included when I examine the BRC records. Speaking to others in the BRC they have typically looked at variants on Coleoptera. Colin suggested looking at both the “Conspicuous ladybird” and the “Non-conspicuous ladybird” records and thus defining the list length from just those recorders searching for ladybirds.

**Comment by drnickisaac** [comment]
I would use all ladybirds together. 
Non-conspicuous ones will certainly have lower detection probabilities, but I don't believe they are recorded in a systematically different way. A good reason to separate would be if there is most people recording inconspicuous species don't bother to record the conspicuous species.
