### ISSUE TITLE
DF website - no longer able to add users

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/BRCtracker#110]
@BirenRathod John Showers and I were trying to add a new user to the DF website, via:
https://www.dipterists.org.uk/admin/people/create

However, that page (which has worked before) now results in an error message "website encountered an error. Please try later".

**Comment by BirenRathod** [comment]
@kitenetter 
Do still see that error on this https://www.dipterists.org.uk/admin/people/create page?

**Comment by kitenetter** [comment]
Yes, got the same error message again.

**Comment by BirenRathod** [comment]
@kitenetter 

I just got accessed this page masquerading as your username and I don't see any errors. do you see error after creating an account or before?

**Comment by kitenetter** [comment]
I'm entering the email address and user name for a new user, and assigning them a temporary password. I tick the box to say they are a member. I then click on save, and get the error message. I think John Showers had the same experience.

**Comment by BirenRathod** [comment]
Ahh right, that is different then what I asked before. I'm looking into that.

**Comment by BirenRathod** [comment]
@kitenetter 
Try again creating user account, it should be fine now.

**Comment by kitenetter** [comment]
Thanks, that's worked okay now. Closing.
