### ISSUE TITLE
Mothnight - archive 2018 public events

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/BRCtracker#111]
Could you arrange for the archive of last year’s (2018) public events from the website and prime the page ready for 2019 please. The teardrops are still showing for last year.

**Comment by BirenRathod** [comment]
@DavidRoy 

Could you elaborate bit more info to this? Which page are we looking for to implement? I found this page -> http://mothnight.info/public-events-list, which is already showing current year events.

**Comment by BirenRathod** [comment]
@DavidRoy 
Map is on now with listed events of 2019.

**Comment by DavidRoy** [comment]
Thanks.  I'll ask others to test
