### ISSUE TITLE
Mothnight - improve form for entering events

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/BRCtracker#113]
Following email discussion with Paul Hill.  Changes required to: http://www.mothnight.info/node/add/event

1. Show this text in red font to make more obvious.
_Zoom in to the map and click to mark the location of the meeting point for your event. You can drag the marker to make corrections. You can ignore the latitude and longitude fields below the map as these are calculated automatically from the marker location._
2. Hide the lat, long values from the form.
3. Add in a place-name search facility.  Google place name search to be used

**Comment by BirenRathod** [comment]
@DavidRoy 
I have implemented this form now. Actions taken by me are below.

1. Text color change to red.
2. Hidden lat long fields.
3. Place search facility have been added. Due to module limitation of autocomplete text field, I have to display number of fields and button to find place.
