### ISSUE TITLE
Update NMRS occupancy trends

### ISSUE THREAD

**Issue by JackHHatfield91** [BiologicalRecordsCentre/BRCtracker#116]
We need to decide whether to update the moth occupancy trends (based on NMRS data). The current trends run to 2016. There is also the issue of whether the NMRS data contains the RIS data.

**Comment by drnickisaac** [comment]
Given the size of the models, we could consider using this to test (i.e. figure out) sequential Monte Carlo methods to update our existing model with the new data. I'm told its' quite straightforward.

**Comment by GPowney** [comment]
TA to contact Les Hill regarding RIS data in NRMS.  If these data are in the NMRS data, CH will filter them out in the database using a similar approach to that used for the Butterfly data.

**Comment by AugustT** [comment]
Emailed Les today, he is on holiday until the 12th August

**Comment by drnickisaac** [comment]
When re-running these, consider including records from 1968 and 1969 so the resulting trends will be comparable directly with RIS

**Comment by drnickisaac** [comment]
I just learned (from Richard Fox) that there is no update to the NMRS data just yet.
More precisely, there is a cleaned version, in which a about 10,000 records were queried during the Atlas production. Some of these 10,000 were rejected, some accepted. 
Given there are 25 million records in total, the "errors" amount to approx <0.04% of the total. The effect on our long term occupancy trends is likely to be unmeasurable for most species. Given that it takes a month to rerun these models, I don't think it's a priority to work with the cleaned dataset.
However, even this cleaned does not contain records after 2016. It will be another 12 months before Les Hill has imported records for 2017, 2018 and 2019. But in early 2021 there will be enough records for another set of occupancy models.
