### ISSUE TITLE
DF website - extend permissions for editor role

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/BRCtracker#117]
For the "editor" role on the DF website, it would be good to enable editors to have more control when creating new pages (especially relevant to new "recording scheme" content types, but also applies to pages in general):
1. Be able to use the "Menu settings" to add a new scheme or page into the main menus
2. Be able to set a page as published or not (to allow draft pages to be worked on as unpublished, before publishing them once they are complete)

**Comment by BirenRathod** [comment]
@kitenetter 
For the "editor" role, It has got adding/editing permission already. I have now enabled the permission of accessing menus & its items, so editor can add links in any menu.

**Comment by kitenetter** [comment]
Thanks @BirenRathod that has enabled the menu settings, but I can't see the tick box for published/unpublished - is it possible to add that as well?

Current choices available to an editor are:

![image](https://user-images.githubusercontent.com/16039111/62537918-7ebdc480-b849-11e9-80e8-c651a88124ac.png)

**Comment by BirenRathod** [comment]
@kitenetter that permission also been amended now. So editor now have got choice to publish or unpublish content.

**Comment by kitenetter** [comment]
Thanks - closing.
