### ISSUE TITLE
DF website - how to stop masquerading?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/BRCtracker#118]
If I masquerade as another user on the DF website, I can no longer see any way of stopping the masquerade and reverting to my own log-in (except by logging out of the website completely). 

I'm sure this used to be possible!

**Comment by BirenRathod** [comment]
@kitenetter 
I have enabled the link for unmasquerade, which will appeared as item in "My account" menu link.

**Comment by kitenetter** [comment]
Thanks - closing.
