### ISSUE TITLE
UK beetle recording website: news content type has text area missing

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/BRCtracker#119]
I'm trying to add a news item via Content - Add content - News:
https://www.coleoptera.org.uk/node/add/news

The page opens up as expected, but the "Body" area is blank and it is not possible to type any text into it.

(I'm using Chrome.)

**Comment by BirenRathod** [comment]
@kitenetter 
I have upgraded the library for text editor, so it should be fine. That was affecting on all contents.

**Comment by kitenetter** [comment]
Great, that's working again now, thanks. Closing.
