### ISSUE TITLE
TSDA ladybirds update

### ISSUE THREAD

**Issue by msjitlal** [BiologicalRecordsCentre/BRCtracker#12]
An update on the data management:

1. BRC records, 1990-2016 extracted;
2. Keep only those records where start and end dates match;
3. GB only records - I used gridref_type = "OSGB" for this;
4. Restricted to records where the precision was 1000 metres, or less;
5. This results in 15,975 monads with Harlequin records - year of first arrival and binary presence for all years has been recorded (object = monads);
6. There are 21,363 monads with non-Harlequin ladybird records, but only 6685 monads with 2+ years, relating to 45,824 survey visits. List length (exc. Harlequin) has been calculated for this, with approx 70% of survey visits of length=1.

The primary concern so far is whether the species list I have extracted is correct. Any name with just the genus I dropped, even if only one species occurs in the current list (I've emailed Helen, who's on leave this week, to clarify). Also there are Adalia records with forma sub-species records and I dropped these (only a handful, though I can see we may wish to retain these).

**Comment by msjitlal** [comment]
I dropped all species records where the genus alone was given. For Adalia, where sub-species forms were given, I have "rounded up" tot he species name.

The 13,926 records (from the total 45,824 records) with no Harlequin record have had year of arrivals et to NA (and annual vectors alls et to zero).

**Comment by msjitlal** [comment]
Also note that as the restrictions I have enforced are that a monad needs to have at least two NON-Harlequin records, most monads with harlequin recorded have been dropped. i.e. 15,975 monads with Harlequin, but only 6685 monads in analysis, as need 2+ years with non-Harlequin data (3389 monads with Harl records; 3296 without Harl records).

**Comment by AugustT** [comment]
@msjitlal I have updated the tags on this issue. I have assigned it to you, added the tag 'TSDA' and linked it to the TSDA A2 project. These are all available on the right hand side. You can do the same with your other Ladybird issue #9

**Comment by drnickisaac** [comment]
I've assigned this issue to the Milestone for 15 March reporting. So let's use this Issue to track progress of the project overall but keep remaining (and emerging new) issues for the technical details.

**Comment by drnickisaac** [comment]
@msjitlal Looks like this issue deals exclusively with data handling and is now resolved. Is that right? If so, please close.
