### ISSUE TITLE
Add category to schemes page on BRC website

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/BRCtracker#120]
On this page:
https://www.brc.ac.uk/recording-schemes

we need a new top-level category for "Monitoring schemes" (that is, at the same level as the current "Botanical schemes", "Vertebrate schemes" etc.). And we will then need to add some new entries in the "Scheme" taxonomy.

Can you give me full editing permissions please (currently I can add or edit Content, bbut not Structure).

**Comment by BirenRathod** [comment]
@kitenetter 
You got now admin rights.
