### ISSUE TITLE
DF website - Editor role unable to edit recording scheme pages

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/BRCtracker#122]
On the DF website, the Editor role has been given permission to edit the "recording scheme" content type:

![image](https://user-images.githubusercontent.com/16039111/74957090-f676c980-53fe-11ea-8d97-7ed12a0037c1.png)

However, users who have been given the editor role are finding that if they try to edit a recording scheme page, the Body section is unavailable:

![image](https://user-images.githubusercontent.com/16039111/74957286-3f2e8280-53ff-11ea-9887-eba565953cd3.png)

Please can you enable editing of the Body text.

**Comment by BirenRathod** [comment]
@kitenetter 

Make sure that body of "recording scheme" content type has got "full html" selected by default.

**Comment by kitenetter** [comment]
Thanks @BirenRathod - new recording scheme content is set to Full HTML by default, but the existing page that I was looking at only had Basic HTML, and now I've changed that it should be fine. Closing.
