### ISSUE TITLE
BMIG website - add account

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/BRCtracker#123]
@BirenRathod please can you add me as an admin to the BMIG website (http://www.bmig.org.uk/). 

Do I need to register first, and if so where do I go to register or log in?

**Comment by BirenRathod** [comment]
@kitenetter 
I have created your account for you. you must be receiving an email by now.

**Comment by kitenetter** [comment]
@BirenRathod as far as I can see I have not received an email, could you resend please?

**Comment by kitenetter** [comment]
Now received thanks - closing.

**Comment by BirenRathod** [comment]
@kitenetter 
I just reactivated your account, did you receive an email?
