### ISSUE TITLE
DF website: can't upload large PDFs

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/BRCtracker#125]
I'm trying to upload some more back issues of the Dipterists Digest, with PDF documents that are 35 to 45 MB. All are failing to upload. There is no error message, and the forms say that they will accept files up to 100 MB, but the upload just doesn't happen.

**Comment by BirenRathod** [comment]
@kitenetter 
This is depend on your internet connection. Some other people experienced similar problem on other website.

**Comment by kitenetter** [comment]
I have no problems uploading much larger files to other websites. Why is this a problem for the DF website, and is there a solution?

I have tried to upload these files several times over a period of many weeks now and they fail every time.

**Comment by BirenRathod** [comment]
@kitenetter 

I just uploaded about 39MB size of PDF file which you can find here -> https://www.dipterists.org.uk/admin/content/media

This is just for your reference, so you can delete after that. So seems that clearly there is no problem of uploading files up to 100MB.

**Comment by kitenetter** [comment]
I tried again just now and the upload worked fine. You must have persuaded it to cooperate @BirenRathod !

Closing.
