### ISSUE TITLE
DF website: membership joining options failing to display

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/BRCtracker#126]
On this page:
https://www.dipterists.org.uk/index.php/join

there should be a block that allows people to choose a membership type and add it to their basket. That block is missing - there is just a message:
[view:list_of_membership]

Please can this be reinstated.

(I thought I'd added this issue a few days ago but I can't find it - apologies if this is a duplicate.)

**Comment by BirenRathod** [comment]
@kitenetter 
The membership list is back now. 
I don't know the reason why has it disappeared? I just re-saved the view and put it back.

**Comment by kitenetter** [comment]
I don't know why it disappeared either! When I first noticed this I did go in to look at the view settings, but I couldn't see anything out of place. I didn't try saving it though, will do that if the problem re-occurs.
