### ISSUE TITLE
DF website: home page image carousel has stopped working

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/BRCtracker#137]
The DF home page normally has a set of scrolling images. Today the images are showing in one long and static column.

Can we return it to the previous view.

**Comment by BirenRathod** [comment]
@kitenetter 
I flushed the cached, so should be fine by now.

**Comment by kitenetter** [comment]
Thanks @BirenRathod - what causes that to happen? Can I flush the cache if it happens again?

**Comment by BirenRathod** [comment]
I upgraded the module, so it needs to clear the cache. Generally when I upgrade the module it should clear the cache but sometime it just waiting to happened by schedule setup by Drupal site.

**Comment by kitenetter** [comment]
Thanks - closing.
