### ISSUE TITLE
modelling update (dynamic multi-species occupancy models)

### ISSUE THREAD

**Issue by msjitlal** [BiologicalRecordsCentre/BRCtracker#15]
1. R=50; nits = 200; nsp =4 - runs within 30 minutes on PC. Output appears sensible; High Rhats for ini.occ[i], but otherwise highest Rhat <2;

2. R=10; nits=500; nsp=8 - after 15 hours crashed due to what appears to be a memory issue:

     Error in unserialize(node$con) : error reading from connection
     Error in serialize(data, node$con) : error writing to connection

**Comment by drnickisaac** [comment]
@msjitlal i think this issue has been superseded by  #20 - if so we should close this one.
