### ISSUE TITLE
Plan for 2018 Indicator

### ISSUE THREAD

**Issue by drnickisaac** [BiologicalRecordsCentre/BRCtracker#18]
@GPowney to outline the steps required for completion.

**Comment by GPowney** [comment]
Timescale for the 2018 UK biodiversity indicators:
- Datasheets: April 30th
- Draft fiche and technical reports: May 16th

- [ ] C4a datasheet
- [ ] C4b datasheet
- [ ] D1c datasheet
- [ ] C4 Fiche and technical report
- [ ] D1c Fiche and technical report
- [ ] Bayesian methods technical report

**Comment by drnickisaac** [comment]
@GPowney please add a note about what was delivered already.
then close this issue (you can leave the checkboxes unticked - no need to delete). Then start a new issue (linking to this one) with what happens next.

**Comment by drnickisaac** [comment]
Gary's report is here: W:\PYWELL_SHARED\Pywell Projects\BRC\_BRC_projects\Indicators\Update on the production of the Biodiversity Indicators 2018.docx
