### ISSUE TITLE
Initial comparison of structured vs unstructured distribution trends in moths

### ISSUE THREAD

**Issue by drnickisaac** [BiologicalRecordsCentre/BRCtracker#2]
The goal is to bring the two sets of distribution data and compare them.
It's dependent on #1 (JASMIN runs of RIS data)
@AugustT - where are the JASMIN runs for NMRS moth data?
Then I'll build a preliminary RStudio project to compare them.

**Comment by AugustT** [comment]
@drnickisaac All outputs are here: W:\PYWELL_SHARED\Pywell Projects\BRC\Tom August\ASSIST\RIS_Moths

I'll add this as a note to the project

**Comment by drnickisaac** [comment]
Moth trends from NMRS are here: \\nercwlctdb.ad.nerc.ac.uk\shared\SHARED1\PYWELL_SHARED\Pywell Projects\BRC\Charlie\1.c. New Model Rerun\4. Outputs\JASMIN\Moths\2. Species info

@CharlieOuthwaite please point me to the annual growth rates derived from these outputs, and the script used to perform the calculations.

**Comment by CharlieOuthwaite** [comment]
@drnickisaac trends in the folder above, I think, are absolute change in occupancy.

1. csv with annual growth rates and abs change for all species called All_sp_annual_growth_rate.csv in:
W:\PYWELL_SHARED\Pywell Projects\BRC\Charlie\1.c. New Model Rerun\6. Indicators and other analyses

This is the most up to date and the table I have been using.  This table has the annual growth rate for each species calculated from the years that have data, from the posterior sample, and include a measure of uncertainty.

2. Script used to calculate growth rate is called 1_Species_Trends_datayrsonly_annual_change.r and can be found here:

W:\PYWELL_SHARED\Pywell Projects\BRC\Charlie\1.c. New Model Rerun\5. Scripts\Analysing results

**Comment by drnickisaac** [comment]
I've compared the two species lists. 515 species names appear in both datasets, but there are >200 in RIS that don't match names in NMRS and vice versa. The mismatches are stored here:

P:\NEC04273_SpeciesDistribution\Workfiles\BRC Range Trends\Abundance-RangeTrend\data

We will need help from @RichardFoxBC to investigate in more detail.

**Comment by AugustT** [comment]
Worth talking to @colinharrower first as he has been helping me with getting the names sorted for the What's Flying Tonight app. There have been a few changes recently with a new checklist that came out. I bet Colin could help us get some of these names straightened out.

**Comment by colinharrower** [comment]
The Rothamsted data in the BRC database includes a column that contains the BRC concept code for that species if known. This field is populated for all of the species that I managed to match to the BRC dictionary, which I think was a relatively large proportion of the total RIS species list. Attached is the output from a query showing the RIS codes/names and their associated BRC codes/names using the concept column.
[ris_moth_to_BRC_names.xlsx](https://github.com/BiologicalRecordsCentre/BRCtracker/files/1767947/ris_moth_to_BRC_names.xlsx)

**Comment by drnickisaac** [comment]
I've had *fun* converting the trend estimates into annual growth rates. Some of them match quite well with what Charlie got from the 1000 samples, but others don't. 

![image](https://user-images.githubusercontent.com/3996072/36800922-93a5b65c-1ca8-11e8-9df3-82fc681803fd.png)

@GPowney to investigate further, please.
P:\NEC04273_SpeciesDistribution\Workfiles\BRC Range Trends\Abundance-RangeTrend\01_process-occmod-output.R

**Comment by AugustT** [comment]
@drnickisaac Just so I'm clear... this is a comparison of the RIS (converted to presence/absence) trends and NMRS trends?

**Comment by drnickisaac** [comment]
@AugustT Sorry, I was not clear. This issue was originally created to compare occupancy model outputs for RIS and NMRS data, as you suggest. However, I also want to compare (#3 ) these trends (especially the RIS ones) with the abundance based trends (from RIS). So I want a trend metric that is broadly comparable to the Annual Growth Rate (AGR) statistic that @colinharrower extracted from the GAI model runs (#13  ). @CharlieOuthwaite has already produced a metric like this for all the occupancy model runs from unstructured data, based on 1000 samples from the posterior distribution of occupancy estimates. However, we don't have an equivalent set of 1000 samples from the occupancy runs you did on the RIS data (#1 ). There are some other minor technical points that make Charlie's metric different from Colin's AGR. So I spent most of 28/2/18 trying to calculate an annual growth rate directly from the BUGS summary output. The plot above shows the growth rate from my calculations plotted against Charlie's pre-existing growth rate. 

Perhaps I should have asked @AugustT already if it's possible/easy/difficult to extract 1000 posteriors from the results in #1.

**Comment by JackHHatfield91** [comment]
close #2
