### ISSUE TITLE
TSDA models update

### ISSUE THREAD

**Issue by msjitlal** [BiologicalRecordsCentre/BRCtracker#20]
Two model runs with R=1 for all 8 species ran successfully on the cluster overnight. Admittedly these were for tiny numbers of iterations (100 and 500), taking 1.7 hrs and 4.4 hrs, respectively. Surprisingly, and perhaps misleadingly, the traceplots for the 500 iteration model are pretty good for some of the parameters, but not the eight species initial occupancy parameters (though 6/8 species have two chains beginning to overlap). These can be found at:

P:\NEC06282_TSDA\A2 Invasive impacts\Results\Cluster\R1_nits500

I have put nine additional model runs on the cluster, incrementing the number of iterations from 1000 to 75,000 (which I estimate may take 3-4 weeks). I think I may add a 100,000 its model, just in case the model runs prove to be quicker than anticipated.

**Comment by msjitlal** [comment]
PS: the large values for the precision parameters disappear when all eight species are entered into the model....

**Comment by msjitlal** [comment]
The 100,000 iteration model may need to be daisy chained, of which I have no experience, so I may need to pick somebody's brains about this issue in the coming days.....

I've also verified with Andrew Everitt that there are no scheduled cluster down times within the next four weeks.

**Comment by CharlieOuthwaite** [comment]
Tom wrote some code for daisy chaining JAGS models in the cluster guides pages: 
https://github.com/NERC-CEH/cluster_guides/wiki

That might help :)

**Comment by msjitlal** [comment]
Thanks Charlie.

**Comment by msjitlal** [comment]
3/10 model runs completed over the weekend, and the run with 5000 iterations is beginning to look promising with respect to parameter convergence. Still the initial occupancy parameters have less evidence of convergence compared to the others (max R hat = 1.4). However, this model is indicating no Harlequin effect on the persistence, which is somewhat surprising.....

**Comment by msjitlal** [comment]
The model with 10,000 iterations has completed. This has very similar parameter estimates (mean, 2.5th and 97.th centiles) compared to the model with 5000 iterations - which as a separate run, is very reassuring. However, the initial occupancy parameters have yet to converge, so there are 15, 20 and 35 thousand iteration models running, all of which should complete by or around 8th March. I estimate the 50,000 its model to complete around the 14th March, which may be too close to the deadline? Note that the models so far have been completing pretty much on my estimated time for completion, or a little bit earlier. 

I tried updating the 5000 its model yesterday with the update function with the additional species-level parameters, but did not get that far, as I had probelms with recompiling the JAGS object. Charlie suggested changing the class of the JAGS output file to rjags (from JAGSUI), but the object would still not recompile. So, to overcome this I have just run a new batch of models (only up to 35,000 its) with the extra parameters. However, it would be good to get to the bottom of this recompile and update issue soon....

**Comment by CharlieOuthwaite** [comment]
Hey Mark, 
Are you using the r2jags or the jagsUI update function?  I was using the r2jags update function which made the recompile necessary and the reclassifying of the out file.  I'm not sure if you need these steps or not with the other package.  I also had to do the following in the r script before it would work:

load.module("dic")

This is just above the line running the update function in the code I sent you yesterday.  Might be worth a try :)

**Comment by msjitlal** [comment]
Model run with 15,000 iterations is looking much better for the parameter convergence for the 8 species-specific initial occupancy parameters (similar distribution to 10,000 its model, which may suggest a degree of convergence).

**Comment by msjitlal** [comment]
Latest update: model with 5000 iterations for all parameters indicates that the Beta1[i] and Beta2[i] have pretty much converged. I also have 35,000 iterations on the cluster for all parameters, which I estimate will complete in about two weeks' time.

I have also started using the update function, and applying this to the model with fewer monitored parameters with 15,000 iterations, and updating with 1000 iterations indicates Beta2[i] convergence.

**Comment by drnickisaac** [comment]
sounds like good progress - thanks for keeping things updated.
@GPowney Please keep an eye on this as I'll need you to take over after Mark leaves.

**Comment by msjitlal** [comment]
Latest model updates:

1. 15,000 iterations, and updating with 5000 iterations indicates Beta1[i] and Beta2[i] convergence; some init.occ[i] and beta0[i] parameters have converged; gamma[i] less so.

2. 35,000 iterations (with species-specific paarmeters not monitored): most parameters have converged - max Rhat = 1.,12;

3. 35,000 iterations (with species-specific parameters that ARE monitored): still running...... another week?

**Comment by msjitlal** [comment]
The 35,000 iterations run with species specific parameters monitored has now completed (way ahead of estimated schedule). All parameters indicate fairly good mixing of chains, even for the gamma parameters. Only one Rhat > 1.10 with max Rhat is 1.23, and 5 out of remaining 53 parms has Rhat 1.05-1.10, with remaining 48/54 parms with Rhat<1.05. Distribution of all parameters are consistent with previous model runs. This is the model run on which the report will be based (it's the longest model run which monitored all parameters). I will send the CSV and traceplots so that you can review before Monday.

Note that the estimates for the eight beta1 parameters appear to buck Helen's expectations for two species.

**Comment by drnickisaac** [comment]
Great news, Mark.
Would you be able to plot the species trajectories over time, as per the 2012 paper? The fitted values figure is for a grid cell where Harmonia arrived in 2004.

**Comment by msjitlal** [comment]
Model with 100,000 iterations took 20.5 days, instead of estimated 35 days, so models are completing in about 60% of estimated time. Unfortunately this model run did not have all parameters monitored.

Model4 subset of models (50, 100, 1000 and 5000 iterations) are on the cluster with a temporal random effect in the persistency model. The model with 50 its has all relevant parameters monitored (the others do not - a rushed oversight!).

**Comment by drnickisaac** [comment]
A word document describing this work is at P:\NEC06282_TSDA\Workfiles\Reporting\March 2018
We'll close this note now and set up a new one when @GPowney gets started.
