### ISSUE TITLE
Register domains for Dipterists Forum

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/BRCtracker#25]
Register:
http://dipterists.org.uk/

and:
http://www.britishflies.org.uk/

both to point to the BRC-hosted site

**Comment by BirenRathod** [comment]
Hello Martin

Thanks for registering the domain names. Could you also make sure that both these domains should have included prefix. So it should accessible with WWW or without WWW. Ideally they should be accessible without WWW prefix.

**Comment by kitenetter** [comment]
http://dipterists.org.uk/ is now registered and linked to the website.

http://www.britishflies.org.uk/ is registered by Chris Raper and will be linked if needed.
