### ISSUE TITLE
Country-specific occupancy trends

### ISSUE THREAD

**Issue by drnickisaac** [BiologicalRecordsCentre/BRCtracker#30]
We have promised a report on the feasibility of country-specific trends from our occupancy models. Clearly Wales and Scotland are the most interesting countries, and we may end up reporting on just these. But we also have the data for England and NI let's do all four for now. In the first instance we should collate the following for each species:
- [x] Precision of trend estimates in each country
- [x] Number of records in each country
- [x] Plots of precision vs number of records for each country, by taxonomic group
- [x] Plots of UK precision vs precision in each country, by taxonomic group
- [x] For 2-3 species, an occupancy plot for each country*
- [ ] For certain taxa, an indicator plot for each country (e.g. bees, hoverflies, dragonflies, bryophytes)
- [x] A short report (possibly in Markdown) describing the results

*include 1 species where country trends are sensible and another where they are not.

**Comment by GPowney** [comment]
Most of these points are addressed in the following document: W:\PYWELL_SHARED\Pywell Projects\BRC\Gary\TSDA\Regional model feasibility\write up

**Comment by GPowney** [comment]
All plots can be found in the following folder: W:\PYWELL_SHARED\Pywell Projects\BRC\Gary\TSDA\Regional model feasibility\outputs.  The number of records for each region are in the following folder: W:\PYWELL_SHARED\Pywell Projects\BRC\Gary\TSDA\Regional model feasibility\data\record_summary.

This is all based on Bee and Hoverfly models.

**Comment by drnickisaac** [comment]
I'm closing this now as the Milestone has passed. We've reported to JNCC, although this work was not included in it.
