### ISSUE TITLE
Enable editing by DF committee members

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/BRCtracker#31]
Some of the committee members are now registered on the new site. It would be good to give them editing rights as soon as possible so they can start transferring content over.

**Comment by BirenRathod** [comment]
@kitenetter 

Any user who has got editor & secretary role can able to add, edit & delete contents.

**Comment by kitenetter** [comment]
@BirenRathod it looks like users with editing rights can add new content, but I don't think they can edit existing content. Can we make that available to them please.

**Comment by BirenRathod** [comment]
Hello @kitenetter, user can only edit and delete contents if they are the owner of their own content. do you want me to make permission more general? so anybody who has got editer right can modify the content.

**Comment by kitenetter** [comment]
I'm pretty sure that there will be a need for several users to be able to edit the main parts of the site - one of the problems with the existing website is that some of the editing could only be done by particular people who weren't always available.

So yes please, do give editors the ability to modify content. Hopefully we can just use one level of permissions and trust people not to edit things they shouldn't! But if it does become problematic we can revisit and perhaps add further levels of permission.

**Comment by BirenRathod** [comment]
That's done.
