### ISSUE TITLE
DF website events

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/BRCtracker#32]
New content type needed for events, to store:
- Event title
- Date
- Time
- Location
- Organiser
- Cost
- Description
- URL
- Flag to link to one of more recording schemes

New views/blocks needed to display above content in three ways:
- Forthcoming events feed on home page
- Events listing page
- Details of individual event

**Comment by BirenRathod** [comment]
The content has been created and event page created for events lists.
