### ISSUE TITLE
DF website news

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/BRCtracker#33]
New content type needed for news, to store:
- [x] Title
- [x] Flag to link to one of more recording schemes
- [x] Body text/images for news story

Example from UK Beetles site:
http://www.coleoptera.org.uk/admin/structure/types/manage/news/fields

New views/blocks needed to display above content in three ways:
- [ ] News feed on home page
- [ ] News page with all news items
- [x] Details of individual news item

**Comment by BirenRathod** [comment]
The news item content created and generated list of page and block.
