### ISSUE TITLE
DF website general tasks

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/BRCtracker#34]
- [x] Implement a new colour scheme based on examples provided by Darwyn Sumner
- [x] Add "latest forum posts" feed to home page (if space allows after other content added e.g. events and news)
- [x] Add Twitter feed to home page for @DipteristsForum
- [x] Add banner images to home page (not constantly scrolling, but ideally a selection of images that change with each page refresh)
- [x] Enable menus at top of page

**Comment by BirenRathod** [comment]
Color scheme implemented
Forum posts added
Enabled menu

**Comment by DavidRoy** [comment]
Please also add an acknowledgement to BRC/CEH for developing and hosting the site.  Perhaps as page footer throughout the site?

Does the site also need a footer with any T&Cs or policy statements?  Any use of cookies for example

**Comment by BirenRathod** [comment]
Logo & reference link have been added. Also Site has got google analytics synced and cookies page has been setup.

**Comment by kitenetter** [comment]
A minor point, but can we make the "Home" menu item clickable?:

![image](https://user-images.githubusercontent.com/16039111/39364199-185063a8-4a25-11e8-8f8e-b9dfada95f31.png)

All other menu items are clickable but I keep clicking on "Home" and getting frustrated!

**Comment by BirenRathod** [comment]
"Home" link is now enabled to link for home page in the menu.

**Comment by BirenRathod** [comment]
Banner image added and home page rearrange, looks bit more appealing.
@kitenetter 
Whenever upload image for banner or on the page, please keep maximum width size 1140px. No need to resize for smaller image, the page will automatically resize it for icon or any other purpose.

**Comment by kitenetter** [comment]
@BirenRathod : request from DF for the pale orange hyperlink text to be made more visible. Suggestion from DF is that we should use W3C Standards to ensure sufficient contrast for readability.

I think we may need to revisit the home page layout, I think the introductory text is now too far down the page, but probably best to wait until we've discussed this with the DF website group.

**Comment by BirenRathod** [comment]
Implemented link text according to W3C standard. Home page has been revamped.
