### ISSUE TITLE
DF website online membership

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/BRCtracker#36]
Add facility for joining online via PayPal.

Enable registration for DF members - presumably this will need to be set up so that if a user requests to register, that request is sent for approval to the DF membership secretary for cross-checking against the offline membership list.

We will need to ensure that DF has an appropriate privacy statement on the website, to cover website registration as well as DF membership.

**Comment by BirenRathod** [comment]
Paypal facility has been added now. 

I need Paypal email and contact address which I could link with payment. Also, need to setup and privacy statement.

**Comment by kitenetter** [comment]
@BirenRathod the membership list has now been supplied and is "CONFIDENTIAL DF members data transfer worksheet_MH edit.xlsx" in:
W:\PYWELL_SHARED\Pywell Projects\BRC\_BRC_projects\Dipterists Forum website\Membership list

I think there are some questions to resolve, including:
- Do we want to retain the 0/1 flags to show who is currently a member and for which options?
- How will we track whether people are subscribing to the current year or the following year?
- Does the format of the spreadsheet align with the attributes that are collected via the online joining form?

**Comment by kitenetter** [comment]
I think that we will need to pre-populate the database with usernames. I think we should use codes rather than names for this, as we don't know what usernames people will wish to use. Can we do a simple sequence such as DF001, DF002 etc. for each user?

**Comment by kitenetter** [comment]
May need to revisit following testing with John Showers. Closing for now.
