### ISSUE TITLE
DF website - content type: Digest

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/BRCtracker#38]
I think this is intended to hold details of individual articles published in DIpterists Digest? If so:
- "Volume title" should be "Volume part" - or alternatively we could include the part number in the main volume number, so that we have vol. 24(1) and 24(2) etc.
- "Editor" - I don't think we need this, the editor is not usually included in any citation, and it's an extra attribute to have to fill in for every article entry
- The section "VOLUMES" should be called "ARTICLES"
- The final button should be "Add Digest's articles"

**Comment by BirenRathod** [comment]
This content has been implemented  and price filed too.
