### ISSUE TITLE
PDF upload features needed

### ISSUE THREAD

**Issue by BirenRathod** [BiologicalRecordsCentre/BRCtracker#40]
Content like Basic page, book & news require a PDF upload feature.

**Comment by BirenRathod** [comment]
PDF filed have added to Basic page, book & news contents. 
Extra image field has been added to Basic page content. This extra field has got image resize and field placement features already included.

**Comment by kitenetter** [comment]
For the PDFs, can we make it possible to hide the uploaded document from being displayed at the foot of the page.

Can we make it possible to set the PDF link to open in a new tab.

**Comment by BirenRathod** [comment]
PDF displayed at the foot has removed. Also, any link has got feature to select the check box called "open in new window" will allow to open any file into new window.
