### ISSUE TITLE
DF website content to add

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/BRCtracker#41]
- [x] Update committee list
- [x] upload latest PDF checklist

**Comment by BirenRathod** [comment]
Hello Martin

New committee members list have been created. That means list will only shows only registered users on the website. 

You could find rest from below list :--

Chairman: Robert Wolton
Vice Chairman: Howard Bentley
Secretary: vacant
Treasurer: Victoria Burton
Membership Secretary: John Showers
Indoor Meetings Secretary: Martin Drake
Publicity Officer: Erica McAlister
Dipterists Digest Editor: Peter Chandler
Bulletin Editor: Darwyn Sumner
Assistant Bulletin Editor: Judy Webb
