### ISSUE TITLE
DF website links to committee members

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/BRCtracker#46]
From this page:
http://dipterists.org.uk/about

If you are logged in as a non-admin user, and click on a committee member name, you get taken to their profile, plus you can see their downloads, but you can't see their contact form.

I think the link for these committee names should go straight to the relevant contact form, not to the profile.

**Comment by BirenRathod** [comment]
I upgraded the link of every users.

**Comment by BirenRathod** [comment]
You are not appear in committee member but you are in other committee member.

**Comment by kitenetter** [comment]
When I'm logged on as me I can't see myself listed!:

![image](https://user-images.githubusercontent.com/16039111/39369956-89538c14-4a35-11e8-9d2b-4fd6af233d01.png)

**Comment by BirenRathod** [comment]
List shows all members regardless of logged in status.
