### ISSUE TITLE
DF website membership categories

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/BRCtracker#47]
Their are four possible membership categories:
- Membership of Dipterists Forum £8 per year
- Subscription to Dipterists Digest £12 per year
- Member plus subscriber £20 per year
- Overseas member (includes Digest subscription) £25 per year

These need to be presented as payment options when people join online, and the membership type needs to be stored in the membership database.

**Comment by kitenetter** [comment]
@kitenetter to get copy of membership list from John Showers - fields needed are:
- username
- name
- address
- email
- member only
- subscriber only
- member + subscriber
- overseas member
- renew date

**Comment by BirenRathod** [comment]
I have implemented the membership module. The user gets three options.
