### ISSUE TITLE
DF website events listings

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/BRCtracker#48]
- [x] Date needs to handle date ranges
- [x] Can the time field be optional. not mandatory? And is there an easier way to type in the time (don't need to go down to seconds!)
- [x] Location map to be enabled
- [x] After clicking on calendar display (e.g. from Home page) the full event details need to be displayed

**Comment by BirenRathod** [comment]
Still require to update location map settings.

**Comment by BirenRathod** [comment]
All done.
