### ISSUE TITLE
Add help menu for DF website logged-on users

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/BRCtracker#52]
For the UK Beetles website we have a help menu that only appears if you are logged on, and in which we are able to put information about how to edit the site, for those people that are doing so.

Can we have something similar for the DF site? I'm not sure if we need to set it up so that some items are visible to any logged on user (e.g. instructions for using the forums), while others are only visible to people with editing rights (e.g. instructions for editing pages or adding content). Maybe we only need one Help menu for everything - it will be obvious to non-editors that they can't make use of the editing instructions?

**Comment by BirenRathod** [comment]
Yes, we could do that. Have you created the help page?

**Comment by kitenetter** [comment]
I haven't, but I can do so if that's the first step. Will set something up this afternoon.

**Comment by BirenRathod** [comment]
Yes, please.

**Comment by kitenetter** [comment]
Basic help page created and added to menu:
http://dipterists.org.uk/help

Sub-pages to follow

**Comment by BirenRathod** [comment]
Hide help link for anonymous users
