### ISSUE TITLE
DF website events listing queries

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/BRCtracker#54]
Is the "Start time" a free text box? If so, can we re-label it as "Start and finish times".

For the event location we have a map window, and it seems to be possible to manually zoom in and find a place, and add a marker at the correct location, However, the text box at the top left of the map doesn't appear to do anything - it is not acting as a search box to find places, and if you type in a location name into that name does not appear on the events page after saving. We do need to have a field that stores the location name and/or address details.

The date display looks odd - ideally the "date to" would only be displayed for events that lasted more than a single day, and it would be better to have the two date field adjacent, not separated by the time field:
![image](https://user-images.githubusercontent.com/16039111/39554191-4a10aa54-4e69-11e8-97a4-492c41bfe4dd.png)

The event that I've just added has ended up with a double entry in the calendar view - is this because I gave a start date and an end date>:
![image](https://user-images.githubusercontent.com/16039111/39554242-9aaade76-4e69-11e8-9567-f3ec2c5765cc.png)

If so I think we need to make it clear that the end date is not needed for single-day events.

**Comment by BirenRathod** [comment]
Yes, The time text filed has re-labeled.
For single day event , no need to add end date.

Display has been amended. for some reason time of event creation was displaying but not in the right format.
