### ISSUE TITLE
DF website Help page menu link visible but pages not accessible to editors

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/BRCtracker#55]
The Help pages that I've added are visible to me, but if I masquerade as another user (who is an editor) the Help menu gets redirected to the home page.

Ideally the Help menu should not be visible at all for non-editors, but all editors whould be able to see the menu and access the pages.

**Comment by BirenRathod** [comment]
Only accessible for Administrator & editor.
