### ISSUE TITLE
Page footers

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/BRCtracker#58]
- Update footer so that it includes DF logo and links to Privacy Notice and a Contact DF form
A draft privacy notice is at http://dipterists.org.uk/privacy-notice (@kitenetter to update)
@kitenetter to confirm what email to use for contact form

- Reword footer to say “Copyright © 2018 Dipterists Forum. Website designed and developed by Dipterists Forum and the Biological Records Centre.” [BRC website to be hyperlinked]

**Comment by kitenetter** [comment]
I have edited the privacy statement page to incorporate text provided by David Roy. It is at http://dipterists.org.uk/privacy-notice (but that currently produces "Page not found" - presumably there is a setting somewhere that needs changing?).

Need to provide a link in the general page footers that goes to the privacy statement.

**Comment by BirenRathod** [comment]
No settings require at present, I making some changes which has affected that. Soon will be available.

**Comment by BirenRathod** [comment]
The works has done and link is working fine.

**Comment by kitenetter** [comment]
@BirenRathod I've added the privacy notice link.

I've also added the DF logo, but I don't know how to make this display properly alongside the CEH one, please can you tidy this up?

**Comment by BirenRathod** [comment]
@kitenetter 

Both logo have been tidy up and works with responsive page.

**Comment by kitenetter** [comment]
@BirenRathod The DF logo has gone missing from the footer, please can we reinstate it.

**Comment by BirenRathod** [comment]
@kitenetter 
It has reinstated now. No idea, why it has disappeared?

**Comment by kitenetter** [comment]
I don't know! I was working on the site last night which was when I noticed it had gone, but I hadn't make any edits to the footer.
