### ISSUE TITLE
Page: Join DF

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/BRCtracker#61]
- Should we hide this page from logged-in users (who will already be members) or is it needed to allow for purchases of back issues and other publications?
- Add option to choose subscription current year or subsequent year (subs to start in January each year)
- Alter wording of payment-related content to describe people as members rather than customers

**Comment by BirenRathod** [comment]
- At present the link is showing under home menu link.
- This option has been added on member's profile page.
- Most of the places the wording "customers" has been amended.

**Comment by kitenetter** [comment]
It's not yet clear to me how new subscribers can specify whether they are subscribing for the current year or subsequent year.

**Comment by kitenetter** [comment]
Closing.
