### ISSUE TITLE
Page: Dipterists Digest

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/BRCtracker#62]
- Make article links display correctly
- Improve display and add search/filter options
- PDFs don’t need price (@kitenetter to edit)
- Investigate options for adding contents (e.g. via bulk upload?) @kitenetter
- Duplicated author names (within the content type) need sorting out

**Comment by kitenetter** [comment]
To do:
- Make it possible to see all the entries, either by adding the ability to go to the next page in the table, or (preferably) making the table longer so that all entries appear on one page. 
- Add the "Series" attribute to the table view.
- At the moment we have the first column unlabelled, this should be "Volume"
- At the moment the second column is labelled "Volumes" but shows no data - presumably we can remove this column?
- Re-order table view so that it runs in sequence, ordered by Series, then Volume, then Volume title

**Comment by kitenetter** [comment]
Need to ensure that we replicate functionality of old site (http://www.dipteristsforum.org.uk/sgb_dipterists_digest.php):
- Page to list all volumes of Digest, based on what we have at http://dipterists.org.uk/digest
- Additional page listing table of contents for all volumes, filterable/searcable by volume/author/subject/date

Maybe this can be implemented within a single page (e.g. with each volume being expandable to show contents) but two pages is fine if easier to implement.

**Comment by kitenetter** [comment]
Not sure if this helps or not, probably not!, but I started trying to set up a new content type for the Digest articles:
http://dipterists.org.uk/admin/structure/types/manage/digest_articles

What I was hoping to do was to import a file into that content type, but I'll need help with how to do this. An example file for import is:
[Contents_24_2.xlsx](https://github.com/BiologicalRecordsCentre/BRCtracker/files/2520662/Contents_24_2.xlsx)

**Comment by kitenetter** [comment]
Update:
We do not need a 'payment by PayPal' option at the moment (the money for the Digest has to go to different accounts than the subscriptions, so this is complicated and can be left for now).

**Comment by BirenRathod** [comment]
@kitenetter 

- We will continue to use the content digest_articles.
- For upload, file format should be like one which I Attached here.
[Digests.xlsx](https://github.com/BiologicalRecordsCentre/BRCtracker/files/2720900/Digests.xlsx)
- On this https://www.dipterists.org.uk/feed/add/upload_volumes page, please do not select no headers check box.

**Comment by kitenetter** [comment]
Closing.
