### ISSUE TITLE
Page: Log in

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/BRCtracker#66]
- Provide explanation of how members can access the site, and what this means for non-members (with link to join DF)

**Comment by kitenetter** [comment]
Text to add to http://dipterists.org.uk/user/login :

If you are **already a member**, and have provided DF with your email address, you should find that you can log in to the website:
•Click on "LOG IN" from the menus above.
•Switch to "RESET YOUR PASSWORD"
•Enter your email address and press "SUBMIT"

An email with a link to log on will be sent to your email address. If this doesn't work please contact Dipterists Forum and we will investigate.

If you are **not yet a member** you can **join here [/join]** - membership is open to anyone with an interest in flies, and new members are always welcome.

**Comment by kitenetter** [comment]
I think I've resolved this one - I've added an additional page at:
http://dipterists.org.uk/log-in-info

This is linked under the "Log-in/log-out" main menu item. 

@BirenRathod if you are happy with this approach please can you close this issue.

**Comment by kitenetter** [comment]
@BirenRathod users are finding the log-in menu behaviour confusing. Can we go back to have a 'normal' log-in menu item, that changes to log-out once you have logged in? And then the link to the additional information about logging in can go under the main log-in menu heading.

**Comment by BirenRathod** [comment]
@kitenetter 
 
Normal login link has been re-established now. The log-in info link added as sub-menu item.

**Comment by kitenetter** [comment]
That's great, thanks. Closing.

**Comment by BirenRathod** [comment]
@kitenetter 

Have a look the latest implementation on log in page.

**Comment by kitenetter** [comment]
That looks good. Is it possible to log in with an email address as an alternative to the user name? People could then choose one or the other, like they can when resetting the password.

**Comment by BirenRathod** [comment]
@kitenetter 

E-mail login has been enabled now, so user can login using their username or password.
