### ISSUE TITLE
New page: Resources for DF members

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/BRCtracker#68]
We will need an area of the website where draft identification keys and other materials can be made available only to logged-in members.

**Comment by kitenetter** [comment]
Page now created at:
http://dipterists.org.uk/members

Rabbit hole "Access denied" setting use to prevent non-member access.

Can we change the text that appears on the "Access denied" page, so that non-members are informed that the page is for members only, and given a link to join?

**Comment by BirenRathod** [comment]
@kitenetter 
You can create another page and use the rabbit hole setting to redirect that page.

**Comment by BirenRathod** [comment]
Also you could put the information about the non-members on that page.

**Comment by kitenetter** [comment]
Thanks, done.

**Comment by kitenetter** [comment]
Sorry, thought I had this page working:
https://www.dipterists.org.uk/for-members

However, it seems that **admins** can see that page, but **members** can't, and I can't see how to change the settings to allow members to view it.

**Comment by kitenetter** [comment]
I think I've resolved this, by adding permissions to enable "Bypass Rabbit Hole action for Content":

![image](https://user-images.githubusercontent.com/16039111/48282128-add90e00-e450-11e8-8bba-f362d538ff75.png)

I'm closing this issue but please let me know if the above settings are not correct @BirenRathod
