### ISSUE TITLE
Download and editing functions for membership list

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/BRCtracker#70]
Enable download of full DF membership list from website.

Enable editing of entries in this list.

**Comment by BirenRathod** [comment]
Members list has been linked with user profile. Every user can see their order details from their account. The list also allow to see orders details.
Also, download features has enabled, Members list now can able to download.

**Comment by kitenetter** [comment]
We may need to return to this following discussion with John Showers but closing for now.
