### ISSUE TITLE
Re-enable top-level menus

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/BRCtracker#71]
The top level menu items on the DF website are currently not functioning, i.e. if you click on them nothing happens.

**Comment by BirenRathod** [comment]
Re-enabled top level menu now.

**Comment by kitenetter** [comment]
Top-level menu items seem to have gone again (except for those that don't have sub-menus).

**Comment by BirenRathod** [comment]
Top level menu links has been re-enabled.
