### ISSUE TITLE
Adding images to standard pages

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/BRCtracker#72]
See:
http://dipterists.org.uk/conservation

On the above page I have added an image, but I want to be able to do three things:
- How do I set it to be right-aligned so that the text flows nicely round the image?
- How do I add a hyperlink that goes to the full size-version of the image?
- How do I add a caption?

**Comment by BirenRathod** [comment]
@kitenetter 

To align right , 
1. Add table
2. In left column add text and right column add images.
Or just click image and press align button from toolbar button 

To add hyperlink
1. Select image and look at the link button like this 
![image](https://user-images.githubusercontent.com/5941255/47370285-50696100-d6dd-11e8-805a-c96eb59e9ddf.png) from toolbar button
2. add link in there.

To add image caption 

1. click image and then click source button from toolbar.
2. Find the <img tag and add data-caption="caption" in there.
Note: replace the caption with suitable caption name.

**Comment by BirenRathod** [comment]
@kitenetter 
Image align and caption have been resolved as we discussed. I will find out about the image zoom option body text.

**Comment by kitenetter** [comment]
I've tried adding some photos to various parts of the website (forums, news, pages). The photo upload behaviour seems to be slightly different in each place; sometimes the alignment options work and sometimes not; sometimes a caption is available and sometimes not. Some places only offer a single upload option via the small image button, others have an additional upload at the foot of the page.

When left- or right-aligned, the text wrap is too close to the photo.

As discussed, it would be great to be able to choose a photo size on upload (e.g. to use a thumbnail) and then have it automatically hyperlinked/zoomed to the original larger image.

Is it possible to have a single consistent method for uploading photos across the site?

**Comment by kitenetter** [comment]
Thanks @BirenRathod I will give that a try and add it to the help pages.

**Comment by kitenetter** [comment]
I've tried using the the above steps. It works, but:
- the right align works, but I can't get the images to align in the centre
- if you embed the image as a thumbnail linked to the media file, save it and then click on the image, it opens up a new page showing a second thumbnail, and then if you click on that second thumbnail it takes you to the original size image. What I'd prefer is for the first thumbnail to go straight to the full image
- ideally I'd like the font for the caption to be different (smaller, maybe italicised) to the main article font
- when right-aligned the text-wrapping comes too close to the image

I still find that Drupal makes it quite hard to work with images, at least in comparison to Wordpress or Blogger, but perhaps that is just a downside of Drupal being more powerful overall. What we have is workable and it's not a priority to spend more time on it but if we can find a more user-friendly option in future that would be great.

**Comment by BirenRathod** [comment]
@kitenetter 
I know the problem is that you have selected the display as thumbnail and selected the image style which is not necessary. just need to select display as full content and that is it. Please see for example page this https://www.dipterists.org.uk/conservation

I might have missed that bit to mentioned in my previous steps.

**Comment by kitenetter** [comment]
The text-wrapping around inserted media images is still too tight, see:
https://www.dipterists.org.uk/bursaries

**Comment by BirenRathod** [comment]
@kitenetter 
text-wrapping around inserted images have been implemented now.

**Comment by kitenetter** [comment]
Closing.
