### ISSUE TITLE
DF forum pages

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/BRCtracker#74]
- Add forum-specific search facility
- Tidy up layout and image handling

**Comment by kitenetter** [comment]
Just to emphasise that the current layout is quite difficult to read. Desirable:
- clearer differentiation between the first post in a thread and the subsequent replies (e.g. indented replies?)
- make it easier to see who has authored which post/comment
- make the "Permalink" links less prominent

**Comment by BirenRathod** [comment]
@kitenetter 
Forum page have amended now. No permalink appears.

**Comment by kitenetter** [comment]
@BirenRathod the layout of the forum pages is looking better, thanks. However, the image handling is still unhelpful, see this example:
https://www.dipterists.org.uk/learn-about-flies/tephritid-possibly-new-somerset

The image is obscured by the reply, and it isn't possible to click on the image to open up a larger size:

![image](https://user-images.githubusercontent.com/16039111/52169020-c09a7080-2729-11e9-8982-f8f7345623c0.png)

When uploading the image via the "Image" button it isn't possible to specify what size it should appear. I know there is the option of using the "Media" button but that is complicated for users and is going to result in a very long and unwieldy list of media files if lots of people use it.

**Comment by BirenRathod** [comment]
@kitenetter
I have implemented styles now. 
Also about uploading image via "image" button is not a problem on forum pages. You can use resize feature found on popup windows of "image" upload button. 
![image](https://user-images.githubusercontent.com/5941255/52203571-7e784880-2869-11e9-9ac3-b4407d1e3bf2.png)

There are some recommended size.
For Thumbnail - 100 x 100
For Medium size - 220 x 220
For Max size - (325 x 325) or (480 x 480)

**Comment by kitenetter** [comment]
Forums mostly working well, three remaining issues:
- Photo upload process is still proving a barrier to users
- Would be good to have a search function within the forums
- Do we need to have a title for every reply to a forum thread? Users are saying that the title is unnecessary, they just want to reply to the initial post in the thread

**Comment by BirenRathod** [comment]
@kitenetter 

- Photo upload process bit more simplified. Now you have got "image properties" option at your right click. 
- Search function added at the top of forum page.
- I removed the title field from all comments. Basically title doesn't need on any comments.

**Comment by kitenetter** [comment]
@BirenRathod I may be doing something wrong, but it appears that the photo upload is now broken. I'm clicking on the button to "Insert images using Imce file manager", and I get taken to the usual File manager window for uploading to the server, but when I click on Upload - Add file, the system seems to searching for the wrong file extension:

![image](https://user-images.githubusercontent.com/16039111/67605831-6ccc2d80-f777-11e9-8a56-989e533408c9.png)

I can change the file extension to all files, which brings the images back into view:

![image](https://user-images.githubusercontent.com/16039111/67605868-8bcabf80-f777-11e9-8aeb-cbd360860f6a.png)

But when I try to open an image I get an error message:

![image](https://user-images.githubusercontent.com/16039111/67605895-a8ff8e00-f777-11e9-917a-8b1a23a03b0d.png)

This is using Firefox.

**Comment by BirenRathod** [comment]
@kitenetter 
Because you got multiple roles allocated, it was restricting you to upload images. I have implemented the permission now. After this amendments, anybody who got a allocated Administrator, Membership secretary, members, committee member & editor roles, could able to upload images in their chosen directory.

**Comment by kitenetter** [comment]
Thanks, that is now working for me. However it is still a complex process for users who wish to be able to upload a photo so that it appears as a thumbnail that can be expanded when clicked on. John van Breda has suggested an alternative approach using the Drupal "Insert" module: http://drupal.org/project/insert

It is likely that DF will commission some extra development work from John to take this forward, so probably no need to spend more time on this at the moment (but let me know if you have any concerns over adopting the Insert module).

**Comment by BirenRathod** [comment]
@kitenetter 
It is not complicated actually.
About thumbnail photo, there is already an example established here. https://www.dipterists.org.uk/general-discussion/thumbnail-practise

After uploading a photo, click again on link icon which appears at top panel, select same image for link which will create icon and zoom/expanding image. 
Also, insert module has already been uploaded and enabled, so you can use that to.

**Comment by kitenetter** [comment]
@BirenRathod the method used in the example that you linked to is considered complicated by our users! Not sure how the insert module takes effect - maybe we can have a quick look at this tomorrow?

**Comment by BirenRathod** [comment]
@kitenetter 
Yes, I will show you that. I think if you create the help page for users would be easier for them too.

**Comment by kitenetter** [comment]
@BirenRathod this is getting very much closer to what we need, excellent! Remaining requests:
- For multiple images, can the thumbnails be arranged in a horizontal strip rather than a vertical one?
- Can there be a small white border between multiple photos?
- When opening up the full-size image into colorbox, at the moment it automatically starts scrolling through the set of images. This can be paused, but it would be better if the default was for it not to auto-scroll in the first place.

**Comment by BirenRathod** [comment]
@kitenetter 
- Horizontal strip has been added now.
- Small white border has now added .
- Auto-scroll stops now.

**Comment by kitenetter** [comment]
That's great @BirenRathod - I'm happy with that and will update the Help page accordingly.

**Comment by BirenRathod** [comment]
@kitenetter 
please close this if you are happy. you can open new issue if requires.

**Comment by kitenetter** [comment]
I'd rather leave it open and assigned to myself until I have finished updating the Help page. Should be able to close next week.

**Comment by BirenRathod** [comment]
No problem, I leave that with you.

**Comment by kitenetter** [comment]
Help page now updated.

@BirenRathod I'm still seeing a title on the replies to forum posts, but I thought we'd decided not to have a title on the replies, see https://github.com/BiologicalRecordsCentre/BRCtracker/issues/74#issuecomment-545431671

**Comment by BirenRathod** [comment]
@kitenetter 
I can't see title on reply to forum posts. Could you send me more details or if you can show me on my computer in my office.

**Comment by kitenetter** [comment]
@BirenRathod see this test reply:

![image](https://user-images.githubusercontent.com/16039111/68117816-4d12d300-fef6-11e9-90e9-c42074327548.png)

**Comment by BirenRathod** [comment]
@kitenetter 
That is not added by users , it has added by comment itself, so it displays by default. There is no default settings for it.

**Comment by BirenRathod** [comment]
@kitenetter 
However, I hid it through CSS styles , so should be fine now.

**Comment by kitenetter** [comment]
Closing.
