### ISSUE TITLE
DF menu settings

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/BRCtracker#75]
- Enable additional level in menu hierarchy, so that there can be two levels visible below the top menu bar
- Nice to have (if easy to do): hide the "unmasquerade" option (under the "My account" menu) from all users except admins

**Comment by BirenRathod** [comment]
@kitenetter 

I have disabled a "unmasquerade" link. It is not actually require for any users. For admin, there is already link appeared at the top menu.

**Comment by BirenRathod** [comment]
@kitenetter 
A multilevel hierarchy has been added in menu. And managed a space little bit.
