### ISSUE TITLE
Adding contact forms to DF website - question

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/BRCtracker#77]
We have set up two generic emails for DF:
- enquiries AT dipterists.org.uk
- membership AT dipterists.org.uk

I'd like to have contact forms that go to these two addresses. To do that, do I need to add both addresses into the "People" table and set up a contact form the same as for any other user?

**Comment by BirenRathod** [comment]
@kitenetter 

You don't need to add these addresses into people list. You need contact forms which you can create through this https://www.dipterists.org.uk/admin/structure/contact/add link where you can add relevant email address.

**Comment by kitenetter** [comment]
Thanks, those two forms are now set up.
