### ISSUE TITLE
Implement a captcha on National Moth Night website

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/BRCtracker#79]
http://www.mothnight.info/node/2

is receiving a lot of spam account registration requests.  Please implement captcha and other options for reducing SPAM accounts

**Comment by BirenRathod** [comment]
@DavidRoy 

I have now enabled the Captcha module along side image captcha feature. I also have added rule for not creating any spam user account from the same email address.

All spam users and theirs contents have been deleted.
