### ISSUE TITLE
DF website - user table

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/BRCtracker#80]
We need to ensure the user table is correct (currently has incorrect email addresses against some people). Suggest this:
- Can you let me have a CSV download of the user (= People) table
- I will highlight the email addresses that need to change (this is quite a small proportion I think)
- I will highlight the entries that we set up with dummy emails - these can be removed
- @BirenRathod to run SQL to update the emails and remove the dummy entries

**Comment by BirenRathod** [comment]
@kitenetter 
if you scroll down the user list page, at bottom of the page, there is a CSV download link. The button too small and it should not at the bottom, but I will resolve that soon.

**Comment by kitenetter** [comment]
Got it thanks, will work on this next.

**Comment by kitenetter** [comment]
@BirenRathod I have now made all the corrections to email addresses, and deleted users with dummy emails. There is no need to run any SQL for this.

However, I note that we have a lot of user names that end with one, or sometime multiple, spaces. This causes failures when trying to save edits, and this is likely to cause problems for users when they log on and try to save their passwords. 

Is it possible to run a query to remove the spaces from the end of user names in the underlying table?

**Comment by BirenRathod** [comment]
@kitenetter 

By giving an option to login with email address, I think user can implement their name by them shelves.
