### ISSUE TITLE
DF website - permissions to add media

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/BRCtracker#81]
The Editor role needs to have permissions to use the "Add media" route for inserting images etc. I have set permissions as shown below, is this correct and are there any others that need adding?

![image](https://user-images.githubusercontent.com/16039111/48192122-d670e300-e33e-11e8-980d-c9e743090cfd.png)

**Comment by BirenRathod** [comment]
@kitenetter 

Thanks for amending those permissions. Very small change, Editor don't need permission for delete any media.

**Comment by kitenetter** [comment]
Have removed delete permission. Closing.
