### ISSUE TITLE
DF website - adjustments to ordering process

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/BRCtracker#83]
- [ ] At the moment, when an order is created, it looks like a notification is being sent to test2@ceh (and I think that gets forwarded to John Showers?). All order notifications should now be going to membership@dipterists.org.uk

- [ ] Notifications that go out to people who place orders are currently coming from enquiries@dipterists.org.uk, this should be membership@dipterists.org.uk

- [ ] At the moment, each time an order is placed both the user and John are getting two identical notifications. I'm not sure why this duplication is happening (and it doesn't seem to be causing any major problems) but if we can prevent the duplication that would be good.

- [ ] After adding a subscription to your cart, you have to click a link that says "Your cart" - that link is not very obvious, can we make it clearer, e.g. by adding something like "Please click on **your cart** to proceed"

- [x] The choice for "current calendar year" and "following calendar year" is fine, but can we remove the "N/A" option?

- [x] When you view an individual order (e.g. https://www.dipterists.org.uk/admin/commerce/orders/415) the information about calendar year is shown as "0" for current year and "1" for following year. Can we change this show that it shows text instead?

 - [x] can we add one more field to the form for Orders, so that users can specify whether they are paying for a new subscription or renewing an existing one. Suggest two tick boxes labelled "New subscription" and "Subscription renewal".

- [x] Can we make the name and address fields mandatory on the order form?

**Comment by BirenRathod** [comment]
@kitenetter 

Issue 1 & 2 - Notification email has been change. The general process is when somebody placed an order, One email sent out of that order to customer and second deliver to enquiries@dipterists.org.uk. 
Becuase I chnaged the email addresses go out via membership@dipterists.org.uk
Issue 3 is relate to about as I explained.

Issue 4 is not possible as this has been hardcoded from the system.
Rest of the issues have been resolved now.
