### ISSUE TITLE
DF website - Orders - Reassign

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/BRCtracker#87]
Two issues:
- Can you give permissions to the memberships secretary role to allow them to use the "Reassign" function
- When using Reassign to link an Order to an existing account, it says that you can search for user name or email:

![image](https://user-images.githubusercontent.com/16039111/48198389-9e729b80-e350-11e8-9a66-14fa2ad63033.png)

However, it appears that only User names can be searched for, using an email address doesn't work.

If it is possible to make the email address searchable that would be good, but we can make do with user name for now.

**Comment by BirenRathod** [comment]
@Membership secretary now have permissions to reassign. At present search box only allow to search the username. Using email is not straight forward.

**Comment by kitenetter** [comment]
Closing.
