### ISSUE TITLE
Mothnight - End of record submission for 2018

### ISSUE THREAD

**Issue by JimBacon** [BiologicalRecordsCentre/BRCtracker#88]
The deadline for data submission is 2nd December 2018.

On the 3rd December or thereafter, remove the submit records block from the home page by
editing http://www.mothnight.info/admin/structure/block/manage/block/5/configure and
setting the region to None for the Moth Night theme.

I don't think we usually do any more than that to discourage new records.

**Comment by BirenRathod** [comment]
@DavidRoy 
Please close this if you don't needed.

**Comment by DavidRoy** [comment]
Thanks
