### ISSUE TITLE
Mothnight - Create new survey for 2019 in the warehouse

### ISSUE THREAD

**Issue by JimBacon** [BiologicalRecordsCentre/BRCtracker#89]
On http://warehouse1.indicia.org.uk go to Lookup Lists > Survey Datasets.
You can find previous surveys by filtering on `Moth Night` in the Title field.

Create a new survey dataset with 
Title: Moth Night 2019
Description: _Dates of the survey_
Website: Moth Night

Edit the following attributes and enable for the new survey just created:

Email: http://warehouse1.indicia.org.uk/index.php/sample_attribute/edit/8
First name: http://warehouse1.indicia.org.uk/index.php/sample_attribute/edit/36
Last name: http://warehouse1.indicia.org.uk/index.php/sample_attribute/edit/58
Moth Night Country: http://warehouse1.indicia.org.uk/index.php/sample_attribute/edit/145
Moth Night Public: http://warehouse1.indicia.org.uk/index.php/sample_attribute/edit/146
Moth Night Participants: http://warehouse1.indicia.org.uk/index.php/sample_attribute/edit/147
Moth Night Site: http://warehouse1.indicia.org.uk/index.php/sample_attribute/edit/151
Moth Night Wind Direction: http://warehouse1.indicia.org.uk/index.php/sample_attribute/edit/152
Moth Night Wind Speed: http://warehouse1.indicia.org.uk/index.php/sample_attribute/edit/153
Moth Night Significant Weather: http://warehouse1.indicia.org.uk/index.php/sample_attribute/edit/154
Moth Night Cloud Cover: http://warehouse1.indicia.org.uk/index.php/sample_attribute/edit/155
Moth Night Maximum Temperature: http://warehouse1.indicia.org.uk/index.php/sample_attribute/edit/156
Moth Night Minimum Temperature: http://warehouse1.indicia.org.uk/index.php/sample_attribute/edit/157

Moth Night Abundance: http://warehouse1.indicia.org.uk/index.php/occurrence_attribute/edit/64
Moth Night Stage: http://warehouse1.indicia.org.uk/index.php/occurrence_attribute/edit/63
Moth Night Method: http://warehouse1.indicia.org.uk/index.php/occurrence_attribute/edit/67
Moth Night Recorder: http://warehouse1.indicia.org.uk/index.php/occurrence_attribute/edit/65
Moth Night Determiner: http://warehouse1.indicia.org.uk/index.php/occurrence_attribute/edit/66

Return to the list of Survey Datasets, locate the new survey and click the link to Setup Attributes. Switch to the list of occurrence attributes and drag them in to the same order as the list above. This ensures the attributes are listed in the correct order in the data entry grid.

I am assuming there is no change to the survey from last year.

**Comment by BirenRathod** [comment]
@DavidRoy 
I have created the survey for 2019 and enabled all these attributes for 2019.

**Comment by BirenRathod** [comment]
@DavidRoy 
This has been tested and gone live today.
