### ISSUE TITLE
TSDA: ladybirds data

### ISSUE THREAD

**Issue by msjitlal** [BiologicalRecordsCentre/BRCtracker#9]
Steph has extracted the data on Harlequins and 8 other ladybird species and compiled no of observations for all records and also complying with the spatial resolution (1km or finer) and stored at the date level. There is a record loss of about 10% for most species:

NAME | All recordss | compliant records | prop compliant
-- | -- | -- | --
Halyzia sedecimguttata | 6395 | 6015 | 0.940578577
Harmonia axyridis | 52485 | 51465 | 0.980565876
Adalia decempunctata | 9439 | 7993 | 0.846805806
Adalia bipunctata | 20686 | 18482 | 0.89345451
Exochomus quadripustulatus | 6864 | 6235 | 0.908362471
Propylea quattuordecimpunctata | 14925 | 13304 | 0.891390285
Coccinella septempunctata | 45409 | 41344 | 0.910480301
Calvia quattuordecimguttata | 5828 | 5064 | 0.868908717
Psyllobora vigintiduopunctata | 6910 | 5997 | 0.867872648

Mark won't be able to start work on the project until early February.

**Comment by AugustT** [comment]
@msjitlal can you have a go at added the labels now? I think I have fixed the issue by adding you to a team which has write privileges.

**Comment by drnickisaac** [comment]
@msjitlal Looks like this issue is resolved, at least until we decide to expand to more species. Close issue?
