### ISSUE TITLE
Mothnight - Update website to use new warehouse survey

### ISSUE THREAD

**Issue by JimBacon** [BiologicalRecordsCentre/BRCtracker#90]
Do not do this before the deadline for 2018 records on 2nd December.
Do this after completing https://github.com/BiologicalRecordsCentre/BRCtracker/issues/89

Clone the following pages and give them new titles by adding 2018 to the end.
http://www.mothnight.info/node/8 - Summary of sightings so far 2018
http://www.mothnight.info/node/5 - Export Your Records 2018
http://www.mothnight.info/node/11 - All Occurrences 2018
http://www.mothnight.info/node/2 - Recording Form 2018
http://www.mothnight.info/node/12 - All Weather 2018
http://www.mothnight.info/node/10 - All Samples 2018
http://www.mothnight.info/node/6 - Edit Your Records 2018

These cloned pages provide access to the surveys of previous years. It might be a good idea to unpublish the previous recording forms to stop records being submitted to them by accident.

Now edit each of the original pages where we need to point them to the new survey created in #89.

http://www.mothnight.info/node/8/edit - Distribution Layer > Distribution layer filter
http://www.mothnight.info/node/5/edit - Report Settings > Preset parameter values
http://www.mothnight.info/node/11/edit - Report Settings > Preset parameter values
http://www.mothnight.info/node/2/edit - Other IForm Parameters > Survey
http://www.mothnight.info/node/12/edit - Report Settings > Preset parameter values
http://www.mothnight.info/node/10/edit - Report Settings > Preset parameter values
http://www.mothnight.info/node/6/edit - Report Settings > Preset parameter values

**Comment by BirenRathod** [comment]
@DavidRoy 
I have created all this pages. The only question is, Is this meant for 2018 or 2019?

**Comment by DavidRoy** [comment]
2019

**Comment by BirenRathod** [comment]
@DavidRoy 
All pages have been updated and created pages for 2018 and new pages linked to 2019 survey.
