### ISSUE TITLE
Mothnight - Change dates of survey on recording form

### ISSUE THREAD

**Issue by JimBacon** [BiologicalRecordsCentre/BRCtracker#91]
There is a custom prebuilt form, mothnight.php, for recording. This exists on the server, wlbrcweb1 at sites\www.brc.ac.uk.mothnight\modules\iform\client_helpers\prebuilt_forms, and is not in any repository. Take care not to accidentally overwrite this if updating the IForm module. There are related files in prebuilt_forms\css, prebuilt_forms\js and prebuilt_forms\lang. (There is also a mothnight_report prebuilt form.)

The prebuilt form declares a custom date control and needs to be updated each year with the dates of the mothnight event. In order to test everything is working in advance to the event I always add a test date which is in the past (since future dates are not allowed). This has to be removed before going live. 

Double check your typing and your copy-pasting because a tiny mistake here can prevent recording working on the day.

**Comment by BirenRathod** [comment]
@DavidRoy 
Changed date on survey form. Please test first if this form works OK. It should not have any problem.

**Comment by BirenRathod** [comment]
@DavidRoy 

Date has been amended. I have also test form which works fine.

**Comment by BirenRathod** [comment]
@DavidRoy 
All dates have been implemented and survey forms gone live from today.
