### ISSUE TITLE
Mothnight - Update logo

### ISSUE THREAD

**Issue by JimBacon** [BiologicalRecordsCentre/BRCtracker#92]
The Mothnight logo contains the dates and needs updating each year.

I copy the current \sites\www.brc.ac.uk.mothnight\files\mothnight_logo.pnp to mothnight_logo_yyyy.png (where yyyy is the year) and replace the logo file with the new one.

I had to recreate the artwork for the logo including locating a font to match the original art work. I chose Dax Regular which is a free download from http://freakfonts.com/fonts/dax-regular-font-download.html. I've attached it in case that resource becomes unavailable.
Also attached are two versions of the 2018 logo in Adobe Fireworks format.

[logo.zip](https://github.com/BiologicalRecordsCentre/BRCtracker/files/2567052/logo.zip)
[DaxRegular.zip](https://github.com/BiologicalRecordsCentre/BRCtracker/files/2567038/DaxRegular.zip)

**Comment by DavidRoy** [comment]
![mn logo 2](https://user-images.githubusercontent.com/2699478/48315103-0a136d80-e5ca-11e8-92fb-fb7e2983704d.JPG)

Need to change the logo / date in the header. Graphic designer to produce a better resolution image, this is a mock-up to use temporarily as need the old header replaced with the new date.

**Comment by DavidRoy** [comment]
The ‘th’ on 20th should be superscript and Anniversary be on a line with the 20, it looks odd as it is.

**Comment by DavidRoy** [comment]
Also change the 19th - 21st text to superscript for 'th' and 'st' as is the standard approach with dates

**Comment by BirenRathod** [comment]
@DavidRoy 

I have amended the logo.

**Comment by BirenRathod** [comment]
Done.

**Comment by DavidRoy** [comment]
The page is now showing a broken image link and no logo!

**Comment by BirenRathod** [comment]
It is now. it takes time to clear out the cache.

**Comment by BirenRathod** [comment]
about 5 min.

**Comment by DavidRoy** [comment]
Thanks. I'll check with Partners that this is now ok

**Comment by DavidRoy** [comment]
Sorry, the dates have changed.  Please replace:
19th to 21st 

with

26th to 28th

**Comment by BirenRathod** [comment]
Date has amended.

**Comment by DavidRoy** [comment]
Thanks
