### ISSUE TITLE
BRC Website: ability to flag multiple recording schemes

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/BRCtracker#94]
Currently, the BRC website only allows a single scheme to be linked to a literature reference.  A growing number of papers are multi-taxa so the website needs to reflect this.  As an example:

This paper only lists BSBI but should be able to link to BNM, BWARS, UKLBS etc
http://www.brc.ac.uk/biblio/agricultural-management-and-climatic-change-are-major-drivers-biodiversity-change-uk

**Comment by BirenRathod** [comment]
@DavidRoy 

I have implemented the field settings, so you could able to add more than one schemes and page will list schemes accordingly.

**Comment by DavidRoy** [comment]
Thanks!
