### ISSUE TITLE
DF website - enable members' use of forums

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/BRCtracker#95]
I hope I have set permissions to allow DF members to add posts in the forums. I have added three permissions to the members role:
- Forum topic: Create new content
- Forum topic: Delete own content
- Forum topic: Edit own content

@BirenRathod are those the correct settings? If so please close this issue.

**Comment by BirenRathod** [comment]
@kitenetter 

Yes, that is about the right permission. I also checked permission for comments and that is fine too.
