### ISSUE TITLE
DF website: users need to edit user names

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/BRCtracker#96]
Logged-in users are able to edit their own account, but at the moment this does not include the ability to edit their user name. Please can this be added.

**Comment by BirenRathod** [comment]
@BirenRathod 
That is about the right and I also checked members could able to add comment.

**Comment by BirenRathod** [comment]
@kitenetter 
The permission has been granted to all authenticated users. It should be like that.
