### ISSUE TITLE
DF website: user account image size

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/BRCtracker#97]
Users report that the limit for adding an image to their user account is 30KB, and they feel that is too restrictive. Can we increase this limit?

![image](https://user-images.githubusercontent.com/16039111/48970116-44383280-f000-11e8-9993-0378d84642a5.png)

**Comment by BirenRathod** [comment]
@kitenetter 

I understand the issue here but this picture is for their profile and if they stick with recommended size (which is 85x85) then it would not exceed the 30 KB limit. (in 30 KB limit, user can upload upto size 100x100 photo) which is still reseanable size for their photo.
