### ISSUE TITLE
DF website: committee roles

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/BRCtracker#98]
How do I assign a committee role to a user in the People table? I need to make some edits and additions to the roles shown here:
https://www.dipterists.org.uk/about

**Comment by BirenRathod** [comment]
@kitenetter 
I don't think assigning a role is any longer a problem for you. Do let me if I do not understand correctly. The list appeared on about page will get filtered every time its upload. So if you assign somebody as committee member, will appear on that list.

**Comment by kitenetter** [comment]
@BirenRathod I can see how to give people a role as a committee member, but I can't see how to specify a particular role within the committee. For example, Rob Wolton is the committee chair, but I can't see anything on his user page that allows me to add or remove the chair role:
https://www.dipterists.org.uk/user/8/edit?destination=/views/ajax%3Fuser%3Dwolton%26status%3DAll%26role%3DAll%26permission%3DAll

**Comment by BirenRathod** [comment]
@kitenetter 
That because we have hidden from edit. You can now see the field called "Job Title" in their account details page.

**Comment by kitenetter** [comment]
Thanks @BirenRathod that looks fine. Closing.
