### ISSUE TITLE
Mothnight - reducing spam accounts

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/BRCtracker#99]
A large number of spam emails are being received by Les Hill (~30 per day).  this is related to setting up accounts and/or registering events.  Captcha and spambot are likely to be needed?

**Comment by BirenRathod** [comment]
@DavidRoy 
Spambot & captacha have been enabled. I found some identical emails from existing spam users which have been added in the rule to restrict user registration.

**Comment by BirenRathod** [comment]
I'm closing this issue as I found no spam users.
